const ADD_HOMEWORK = "ADD_HOMEWORK"
const REMOVE_HOMEWORK = "REMOVE_HOMEWORK"
const UPDATE_HOMEWORK = "UPDATE_HOMEWORK"
const CHANGE_STATUS_COMPLETE = "CHANGE_STATUS_COMPLETE"

export {ADD_HOMEWORK,REMOVE_HOMEWORK,UPDATE_HOMEWORK, CHANGE_STATUS_COMPLETE}